### ISSUE TITLE
Assessment: peer feedback 2

### ISSUE THREAD

**Issue by ReiniervanLimpt** [CountNick/web-app-from-scratch-1920#14]
Functions have good corresponding names, the getData function looks promising, this could become the module i spoke bout in the other peer feedback issue i submitted earlier!

Code hasnt been broken up into modules yet but thank to good function naming  i assume you can bundle functions easily.

Json data is fetched and used to route the user, i would recommend splitting this up by having a module just for fetching data.

https://github.com/CountNick/web-app-from-scratch-1920/blob/222ed4f5f3f5a06d3dc14af7355639028d584d26/js/app.js#L42-L56

Other than that the router seems te be working based on the requsted id for detail rendering, i did not manage to do that yet so thanks! :^) 

No user feedback applied yet, but im sure you will

your getting there bud, good luck

**Comment by CountNick** [comment]
I ended up making a async function, that i use in the router. The reason my router is dependant on data is because i need to fetch all data in order to render something to the page.

* [async function](https://github.com/CountNick/web-app-from-scratch-1920/blob/master/js/modules/api.js)

* [router](https://github.com/CountNick/web-app-from-scratch-1920/blob/master/js/modules/router.js)
